### ISSUE TITLE
ModuleNotFoundError: No module named 'sparse_conv'

### ISSUE THREAD

**Issue by Greatxcw** [Cuogeihong/CEASC#15]
作者你好，首先非常感谢您优秀的工作，我在复现您的代码的时候碰到以下问题：
/usr/local/lib/python3.8/dist-packages/mmdet/utils/compat_config.py:28: UserWarning: config is now expected to have a `runner` section, please set `runner` in your config.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/mmdet/utils/setup_env.py:38: UserWarning: Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/mmdet/utils/setup_env.py:48: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
Traceback (most recent call last):
  File "tools/test.py", line 270, in <module>
    main()
  File "tools/test.py", line 213, in main
    dataset = build_dataset(cfg.data.test)
  File "/usr/local/lib/python3.8/dist-packages/mmdet/datasets/builder.py", line 82, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/usr/local/lib/python3.8/dist-packages/mmcv/utils/registry.py", line 58, in build_from_cfg
    raise KeyError(
KeyError: 'UAVDataset is not in the dataset registry'
希望您能帮我看一下

**Comment by Greatxcw** [comment]
作者您好，上面那个问题我解决了，我把之前环境中下载的mmdet卸载，然后引用代码中提供的mmdet文件夹就解决问题了，然后我重新运行test.py文件，发现又出现下面的错误：
Traceback (most recent call last):
  File "tools/test.py", line 17, in <module>
    from mmdet.apis import multi_gpu_test, single_gpu_test
  File "/data/CEASC-main/mmdet/apis/__init__.py", line 2, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/data/CEASC-main/mmdet/apis/inference.py", line 13, in <module>
    from mmdet.datasets import replace_ImageToTensor
  File "/data/CEASC-main/mmdet/datasets/__init__.py", line 13, in <module>
    from .utils import (NumClassCheckHook, get_loading_pipeline,
  File "/data/CEASC-main/mmdet/datasets/utils.py", line 11, in <module>
    from mmdet.models.dense_heads import GARPNHead, RPNHead
  File "/data/CEASC-main/mmdet/models/__init__.py", line 7, in <module>
    from .dense_heads import *  # noqa: F401,F403
  File "/data/CEASC-main/mmdet/models/dense_heads/__init__.py", line 44, in <module>
    from .fsaf_dy_head import FSAFDYHead
  File "/data/CEASC-main/mmdet/models/dense_heads/fsaf_dy_head.py", line 11, in <module>
    from .retina_dy_head import RetinaDYHead
  File "/data/CEASC-main/mmdet/models/dense_heads/retina_dy_head.py", line 9, in <module>
    from .cuda_dynamic_conv_module import DyConv2D
  File "/data/CEASC-main/mmdet/models/dense_heads/cuda_dynamic_conv_module.py", line 6, in <module>
    from .sparse_conv_net import *
  File "/data/CEASC-main/mmdet/models/dense_heads/sparse_conv_net.py", line 17, in <module>
    import sparse_conv
ModuleNotFoundError: No module named 'sparse_conv'
但是我按照您提供步骤下载了sparse_conv了，请问这是什么原因呢

**Comment by Cuogeihong** [comment]
可以在当前conda环境下通过conda list命令检查是否有"sparse-conv 0.0.0"这一模块，如果没有的话分别检查一下安装是否在当前的conda下，或者安装sparse_conv的时候有没有报错

**Comment by Greatxcw** [comment]
非常感谢作者您的回复，我是在服务器docker下复现的代码，我按照您提供的方法下载了sparse_conv，也显示下载成功了，但是pip list的时候在环境没有看到"sparse-conv 0.0.0"这一模块，于是我尝试着在sparse_conv_net.py文件中导入Sparse_conv文件夹的路径，就成功了。

**Comment by Bonaparte12138** [comment]
UAVDataset is not in the dataset registry咋解决的，我运行train也遇到了这个问题，我的mmdet是2.24.1啊
