### ISSUE TITLE
安装Sparse_conv时出现错误

### ISSUE THREAD

**Issue by Czeni1** [Cuogeihong/CEASC#23]
您好，我在安装SC模块时，运行python setup.py install命令时，出现以下错误，是因为什么呢，期待您的答复！
D:\Anaconda3\envs\CEASC\lib\site-packages\torch\include\pybind11\detail/common.h(152): warning C4005: 'HAVE_SNPRINTF': macro redefinition
D:\Anaconda3\envs\CEASC\include\pyerrors.h(315): note: see previous definition of 'HAVE_SNPRINTF'
sparse_conv_cuda.cpp(11): fatal error C1083: Cannot open include file: 'sys/time.h': No such file or directory
error: command 'D:\\vs20190\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

**Comment by Cuogeihong** [comment]
可以删掉这些代码
https://github.com/Cuogeihong/CEASC/blob/2abfd1a99f1b0fe1ed3d51588b64549e1584da50/Sparse_conv/sparse_conv_cuda.cpp#L11

https://github.com/Cuogeihong/CEASC/blob/2abfd1a99f1b0fe1ed3d51588b64549e1584da50/Sparse_conv/sparse_conv_cuda.cpp#L71-L78

**Comment by Czeni1** [comment]
> 可以删掉这些代码
> 
> https://github.com/Cuogeihong/CEASC/blob/2abfd1a99f1b0fe1ed3d51588b64549e1584da50/Sparse_conv/sparse_conv_cuda.cpp#L11
> 
> https://github.com/Cuogeihong/CEASC/blob/2abfd1a99f1b0fe1ed3d51588b64549e1584da50/Sparse_conv/sparse_conv_cuda.cpp#L71-L78

非常感谢您的回答，但是我在运行train.py的时候出现了这种错误：
Traceback (most recent call last):
  File "tools/train.py", line 237, in <module>
    main()
  File "tools/train.py", line 211, in main
    model.init_weights()
  File "D:\Anaconda3\envs\CEASC\lib\site-packages\mmcv\runner\base_module.py", line 116, in init_weights
    m.init_weights()
  File "D:\Anaconda3\envs\CEASC\lib\site-packages\mmcv\runner\base_module.py", line 105, in init_weights
    initialize(self, self.init_cfg)
  File "D:\Anaconda3\envs\CEASC\lib\site-packages\mmcv\cnn\utils\weight_init.py", line 613, in initialize
    _initialize(module, cp_cfg)
  File "D:\Anaconda3\envs\CEASC\lib\site-packages\mmcv\cnn\utils\weight_init.py", line 517, in _initialize
    func(module)
  File "D:\Anaconda3\envs\CEASC\lib\site-packages\mmcv\cnn\utils\weight_init.py", line 489, in __call__
    load_checkpoint(
  File "D:\Anaconda3\envs\CEASC\lib\site-packages\mmcv\runner\checkpoint.py", line 581, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "D:\Anaconda3\envs\CEASC\lib\site-packages\mmcv\runner\checkpoint.py", line 520, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "D:\Anaconda3\envs\CEASC\lib\site-packages\mmcv\runner\checkpoint.py", line 285, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "D:\Anaconda3\envs\CEASC\lib\site-packages\mmcv\runner\checkpoint.py", line 425, in load_from_torchvision
    model_urls = get_torchvision_models()
  File "D:\Anaconda3\envs\CEASC\lib\site-packages\mmcv\runner\checkpoint.py", line 132, in get_torchvision_models
    model_urls = mmcv.load(json_path)
  File "D:\Anaconda3\envs\CEASC\lib\site-packages\mmcv\fileio\io.py", line 57, in load
    with StringIO(file_client.get_text(file)) as f:
  File "D:\Anaconda3\envs\CEASC\lib\site-packages\mmcv\fileio\file_client.py", line 1028, in get_text
    return self.client.get_text(filepath, encoding)
  File "D:\Anaconda3\envs\CEASC\lib\site-packages\mmcv\fileio\file_client.py", line 552
找不到这个文件，我文件夹里没有这个文件，而且我的环境设置的是pytorch1.13.1，torchvision版本为0.14，CUDA11.7，出现这个错误的原因是因为我pytorch版本问题嘛，还是因为train.py中的model.init_weights()函数呢？或者其他原因，麻烦您啦！感谢您的回答！

**Comment by Czeni1** [comment]
> 可以删掉这些代码
> 
> https://github.com/Cuogeihong/CEASC/blob/2abfd1a99f1b0fe1ed3d51588b64549e1584da50/Sparse_conv/sparse_conv_cuda.cpp#L11
> 
> https://github.com/Cuogeihong/CEASC/blob/2abfd1a99f1b0fe1ed3d51588b64549e1584da50/Sparse_conv/sparse_conv_cuda.cpp#L71-L78

谢谢您的答复，我的环境是CUDA11.3，pytorch1.10.1，mmdet和mmcv都是和您一样的，但出现了这种错误，为什么呢？
(SC) C:\Users\Administrator\Desktop\CEASC-main>python tools/train.py configs/UAV/dynamic_gfl_res18_visdrone.py --work-dir th
Traceback (most recent call last):
  File "tools/train.py", line 17, in <module>
    from mmdet.apis import init_random_seed, set_random_seed, train_detector
  File "D:\Anaconda3\envs\SC\lib\site-packages\mmdet-2.24.1-py3.8.egg\mmdet\apis\__init__.py", line 2, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "D:\Anaconda3\envs\SC\lib\site-packages\mmdet-2.24.1-py3.8.egg\mmdet\apis\inference.py", line 8, in <module>
    from mmcv.ops import RoIPool
  File "D:\Anaconda3\envs\SC\lib\site-packages\mmcv\ops\__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "D:\Anaconda3\envs\SC\lib\site-packages\mmcv\ops\active_rotated_filter.py", line 8, in <module>
    ext_module = ext_loader.load_ext(
  File "D:\Anaconda3\envs\SC\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "D:\Anaconda3\envs\SC\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing _ext: 找不到指定的程序。

**Comment by lili1052** [comment]
你好，请问你后来解决这个问题了吗
