### ISSUE TITLE
版本问题

### ISSUE THREAD

**Issue by Czeni1** [Cuogeihong/CEASC#24]
您好，我一开始用了CUDA11.7，pytorch1.13.1，mmcv-full1.5.1，mmdet2.24.1，测试mmdet也显示是安装成功了，之后运行train.py，出现了以下错误：
  File "tools/train.py", line 237, in <module>
    main()
  File "tools/train.py", line 211, in main
    model.init_weights()
  File "D:\Anaconda3\envs\xxm\lib\site-packages\mmcv\runner\base_module.py", line 116, in init_weights
    m.init_weights()
  File "D:\Anaconda3\envs\xxm\lib\site-packages\mmcv\runner\base_module.py", line 105, in init_weights
    initialize(self, self.init_cfg)
  File "D:\Anaconda3\envs\xxm\lib\site-packages\mmcv\cnn\utils\weight_init.py", line 613, in initialize
    _initialize(module, cp_cfg)
  File "D:\Anaconda3\envs\xxm\lib\site-packages\mmcv\cnn\utils\weight_init.py", line 517, in _initialize
    func(module)
  File "D:\Anaconda3\envs\xxm\lib\site-packages\mmcv\cnn\utils\weight_init.py", line 489, in __call__
    load_checkpoint(
  File "D:\Anaconda3\envs\xxm\lib\site-packages\mmcv\runner\checkpoint.py", line 581, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "D:\Anaconda3\envs\xxm\lib\site-packages\mmcv\runner\checkpoint.py", line 520, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "D:\Anaconda3\envs\xxm\lib\site-packages\mmcv\runner\checkpoint.py", line 285, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "D:\Anaconda3\envs\xxm\lib\site-packages\mmcv\runner\checkpoint.py", line 425, in load_from_torchvision
    model_urls = get_torchvision_models()
  File "D:\Anaconda3\envs\xxm\lib\site-packages\mmcv\runner\checkpoint.py", line 132, in get_torchvision_models
    model_urls = mmcv.load(json_path)
  File "D:\Anaconda3\envs\xxm\lib\site-packages\mmcv\fileio\io.py", line 57, in load
    with StringIO(file_client.get_text(file)) as f:
  File "D:\Anaconda3\envs\xxm\lib\site-packages\mmcv\fileio\file_client.py", line 1028, in get_text
    return self.client.get_text(filepath, encoding)
  File "D:\Anaconda3\envs\xxm\lib\site-packages\mmcv\fileio\file_client.py", line 552, in get_text
    with open(filepath, 'r', encoding=encoding) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Anaconda3\\envs\\xxm\\lib\\site-packages\\mmcv\\model_zoo/torchvision_0.12.json'

缺少这个torchvision0.12.json文件，我看了目录，确实没有这个文件，于是我想是不是我版本问题，所以我又重新创建了虚拟环境，在自己虚拟环境下安装了CUDA11.3，pytorch1.10.1，mmcv-ful1.5.1，mmdet2.24.1，但在测试mmdet是否安装成功的时候，显示这种错误，但我pip list看了是存在sparse-conv0.0.0。所以我在想是我CUDA的问题吗，一台服务器不能有两个CUDA吗，而且我是在我虚拟环境中安装的（呜呜呜，救救孩子吧，周一开组会汇报，非常感谢非常感谢非常感谢！！！）

Traceback (most recent call last):
  File "demo/image_demo.py", line 5, in <module>
    from mmdet.apis import (async_inference_detector, inference_detector,
  File "D:\Anaconda3\envs\amm\lib\site-packages\mmdet-2.24.1-py3.8.egg\mmdet\apis\__init__.py", line 2, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "D:\Anaconda3\envs\amm\lib\site-packages\mmdet-2.24.1-py3.8.egg\mmdet\apis\inference.py", line 13, in <module>
    from mmdet.datasets import replace_ImageToTensor
  File "D:\Anaconda3\envs\amm\lib\site-packages\mmdet-2.24.1-py3.8.egg\mmdet\datasets\__init__.py", line 13, in <module>
    from .utils import (NumClassCheckHook, get_loading_pipeline,
  File "D:\Anaconda3\envs\amm\lib\site-packages\mmdet-2.24.1-py3.8.egg\mmdet\datasets\utils.py", line 11, in <module>
    from mmdet.models.dense_heads import GARPNHead, RPNHead
  File "D:\Anaconda3\envs\amm\lib\site-packages\mmdet-2.24.1-py3.8.egg\mmdet\models\__init__.py", line 7, in <module>
    from .dense_heads import *  # noqa: F401,F403
  File "D:\Anaconda3\envs\amm\lib\site-packages\mmdet-2.24.1-py3.8.egg\mmdet\models\dense_heads\__init__.py", line 44, in <module>
    from .fsaf_dy_head import FSAFDYHead
  File "D:\Anaconda3\envs\amm\lib\site-packages\mmdet-2.24.1-py3.8.egg\mmdet\models\dense_heads\fsaf_dy_head.py", line 11, in <module>
    from .retina_dy_head import RetinaDYHead
  File "D:\Anaconda3\envs\amm\lib\site-packages\mmdet-2.24.1-py3.8.egg\mmdet\models\dense_heads\retina_dy_head.py", line 9, in <module>
    from .cuda_dynamic_conv_module import DyConv2D
  File "D:\Anaconda3\envs\amm\lib\site-packages\mmdet-2.24.1-py3.8.egg\mmdet\models\dense_heads\cuda_dynamic_conv_module.py", line 6, in <module>
    from .sparse_conv_net import *
  File "D:\Anaconda3\envs\amm\lib\site-packages\mmdet-2.24.1-py3.8.egg\mmdet\models\dense_heads\sparse_conv_net.py", line 17, in <module>
    import sparse_conv
ImportError: DLL load failed while importing sparse_conv: 找不到指定的程序。

**Comment by Cuogeihong** [comment]
有可能是你的sparse-conv安装的虚拟环境和最新的虚拟环境不匹配，应该在最新的虚拟环境下执行python setup.py install

**Comment by Cuogeihong** [comment]
可以尝试在linux服务器上进行实验，会比windows系统下做更好

**Comment by Czeni1** [comment]
> 可以尝试在linux服务器上进行实验，会比windows系统下做更好
好嘞好嘞，已经跑起来啦，非常感谢！！！

**Comment by Czeni1** [comment]
> 可以尝试在linux服务器上进行实验，会比windows系统下做更好

您好，我还想再问一下，那个AMM模块还有CE-GN是在gfl_dy_head.py这个文件里面嘛？我怎么找不到在哪呀？

**Comment by Cuogeihong** [comment]
AMM在这里https://github.com/Cuogeihong/CEASC/blob/2abfd1a99f1b0fe1ed3d51588b64549e1584da50/mmdet/models/dense_heads/gfl_dy_head.py#L468-L485
CE-GN在[sparse_conv_net.py](https://github.com/Cuogeihong/CEASC/blob/main/mmdet/models/dense_heads/sparse_conv_net.py)和[cuda_dynamic_conv_module.py](https://github.com/Cuogeihong/CEASC/blob/main/mmdet/models/dense_heads/cuda_dynamic_conv_module.py)

**Comment by Czeni1** [comment]
> AMM在这里
> 
> https://github.com/Cuogeihong/CEASC/blob/2abfd1a99f1b0fe1ed3d51588b64549e1584da50/mmdet/models/dense_heads/gfl_dy_head.py#L468-L485
> 
> 
> CE-GN在[sparse_conv_net.py](https://github.com/Cuogeihong/CEASC/blob/main/mmdet/models/dense_heads/sparse_conv_net.py)和[cuda_dynamic_conv_module.py](https://github.com/Cuogeihong/CEASC/blob/main/mmdet/models/dense_heads/cuda_dynamic_conv_module.py)

好嘞好嘞，谢谢您，感恩的心！！！
